project:
  type: website
  output-dir: "."

website:
  title: "Finance & Computing"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Big Data for Finance Project"
        contents:
          - href: EmentaBigDataFinProj.qmd
            text: "Ementa"
          - href: introportfoliogithubpages.qmd
            text: "Criando seu portfolio numa Github page"
          - href: presFAE.qmd
            text: "Análise de Dados do Mercado Financeiro: utilizando R ou Python com ferramentas de Big Data"
          - href: Apres_encontro2.qmd
            text: "To do list segundo encontro"
          - href: Apres_encontro3.qmd
            text: "To do list terceiro encontro"
          - href: Apres_encontro4.qmd
            text: "Agenda quarto encontro"
          - href: Apres_encontro5.qmd
            text: "Agenda quinto encontro"
      - section: "Risk Management"
        contents:
          - href: EmentaRiskMng.qmd
            text: "Ementa"

      - section: "Programação Computacional"
        contents:
          - href: EmentaProgComp.qmd
            text: "Ementa"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

